# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-17 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='category',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='permission.Category'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='employee',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='permission.Employee'),
        ),
    ]
