# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-18 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_auto_20180717_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='user',
        ),
    ]
