# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-19 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0004_auto_20180718_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Perizinan',
        ),
    ]
